[COREGEN.VHDL Component Instantiation.mux8x4bus]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux8x4bus"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(3 downto 0);"
text007="    MB: IN std_logic_VECTOR(3 downto 0);"
text008="    MC: IN std_logic_VECTOR(3 downto 0);"
text009="    MD: IN std_logic_VECTOR(3 downto 0);"
text010="    ME: IN std_logic_VECTOR(3 downto 0);"
text011="    MF: IN std_logic_VECTOR(3 downto 0);"
text012="    MG: IN std_logic_VECTOR(3 downto 0);"
text013="    MH: IN std_logic_VECTOR(3 downto 0);"
text014="    S: IN std_logic_VECTOR(2 downto 0);"
text015="    O: OUT std_logic_VECTOR(3 downto 0));"
text016="end component;"
text017=""
text018=""
text019=""
text020="-- Synplicity black box declaration"
text021="attribute syn_black_box : boolean;"
text022="attribute syn_black_box of mux8x4bus: component is true;"
text023=""
text024=" "
text025="-------------------------------------------------------------"
text026=" "
text027="-- The following code must appear in the VHDL architecture body."
text028="-- Substitute your own instance name and net names."
text029=" "
text030="your_instance_name : mux8x4bus"
text031="        port map ("
text032="            MA => MA,"
text033="            MB => MB,"
text034="            MC => MC,"
text035="            MD => MD,"
text036="            ME => ME,"
text037="            MF => MF,"
text038="            MG => MG,"
text039="            MH => MH,"
text040="            S => S,"
text041="            O => O);"
text042=" "
[COREGEN.VERILOG Component Instantiation.mux8x4bus]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux8x4bus YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .MC(MC),"
text010="    .MD(MD),"
text011="    .ME(ME),"
text012="    .MF(MF),"
text013="    .MG(MG),"
text014="    .MH(MH),"
text015="    .S(S),"
text016="    .O(O));"
text017=""
text018=" "
[COREGEN.VHDL Component Instantiation.mux2to1_4bit]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux2to1_4bit"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(15 downto 0);"
text007="    MB: IN std_logic_VECTOR(15 downto 0);"
text008="    S: IN std_logic_VECTOR(0 downto 0);"
text009="    O: OUT std_logic_VECTOR(15 downto 0));"
text010="end component;"
text011=""
text012=""
text013=""
text014="-- Synplicity black box declaration"
text015="attribute syn_black_box : boolean;"
text016="attribute syn_black_box of mux2to1_4bit: component is true;"
text017=""
text018=" "
text019="-------------------------------------------------------------"
text020=" "
text021="-- The following code must appear in the VHDL architecture body."
text022="-- Substitute your own instance name and net names."
text023=" "
text024="your_instance_name : mux2to1_4bit"
text025="        port map ("
text026="            MA => MA,"
text027="            MB => MB,"
text028="            S => S,"
text029="            O => O);"
text030=" "
[COREGEN.VERILOG Component Instantiation.mux2to1_4bit]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux2to1_4bit YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .S(S),"
text010="    .O(O));"
text011=""
text012=" "
[COREGEN.VHDL Component Instantiation.mux2to1]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux2to1"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(15 downto 0);"
text007="    MB: IN std_logic_VECTOR(15 downto 0);"
text008="    S: IN std_logic_VECTOR(0 downto 0);"
text009="    O: OUT std_logic_VECTOR(15 downto 0));"
text010="end component;"
text011=""
text012=""
text013=""
text014="-- Synplicity black box declaration"
text015="attribute syn_black_box : boolean;"
text016="attribute syn_black_box of mux2to1: component is true;"
text017=""
text018=" "
text019="-------------------------------------------------------------"
text020=" "
text021="-- The following code must appear in the VHDL architecture body."
text022="-- Substitute your own instance name and net names."
text023=" "
text024="your_instance_name : mux2to1"
text025="        port map ("
text026="            MA => MA,"
text027="            MB => MB,"
text028="            S => S,"
text029="            O => O);"
text030=" "
[COREGEN.VERILOG Component Instantiation.mux2to1]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux2to1 YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .S(S),"
text010="    .O(O));"
text011=""
text012=" "
[COREGEN.VHDL Component Instantiation.mux2to1__4bit]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux2to1__4bit"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(3 downto 0);"
text007="    MB: IN std_logic_VECTOR(3 downto 0);"
text008="    S: IN std_logic_VECTOR(0 downto 0);"
text009="    O: OUT std_logic_VECTOR(3 downto 0));"
text010="end component;"
text011=""
text012=""
text013=""
text014="-- Synplicity black box declaration"
text015="attribute syn_black_box : boolean;"
text016="attribute syn_black_box of mux2to1__4bit: component is true;"
text017=""
text018=" "
text019="-------------------------------------------------------------"
text020=" "
text021="-- The following code must appear in the VHDL architecture body."
text022="-- Substitute your own instance name and net names."
text023=" "
text024="your_instance_name : mux2to1__4bit"
text025="        port map ("
text026="            MA => MA,"
text027="            MB => MB,"
text028="            S => S,"
text029="            O => O);"
text030=" "
[COREGEN.VERILOG Component Instantiation.mux2to1__4bit]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux2to1__4bit YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .S(S),"
text010="    .O(O));"
text011=""
text012=" "
[COREGEN.VHDL Component Instantiation.mux3_4]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux3_4"
text005="    port ("
text006="    M: IN std_logic_VECTOR(2 downto 0);"
text007="    S: IN std_logic_VECTOR(1 downto 0);"
text008="    O: OUT std_logic);"
text009="end component;"
text010=""
text011=""
text012=""
text013="-- Synplicity black box declaration"
text014="attribute syn_black_box : boolean;"
text015="attribute syn_black_box of mux3_4: component is true;"
text016=""
text017=" "
text018="-------------------------------------------------------------"
text019=" "
text020="-- The following code must appear in the VHDL architecture body."
text021="-- Substitute your own instance name and net names."
text022=" "
text023="your_instance_name : mux3_4"
text024="        port map ("
text025="            M => M,"
text026="            S => S,"
text027="            O => O);"
text028=" "
[COREGEN.VERILOG Component Instantiation.mux3_4]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux3_4 YourInstanceName ("
text007="    .M(M),"
text008="    .S(S),"
text009="    .O(O));"
text010=""
text011=" "
[COREGEN.VHDL Component Instantiation.mux3to1_4bits]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux3to1_4bits"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(3 downto 0);"
text007="    MB: IN std_logic_VECTOR(3 downto 0);"
text008="    MC: IN std_logic_VECTOR(3 downto 0);"
text009="    MD: IN std_logic_VECTOR(3 downto 0);"
text010="    S: IN std_logic_VECTOR(1 downto 0);"
text011="    O: OUT std_logic_VECTOR(3 downto 0));"
text012="end component;"
text013=""
text014=""
text015=""
text016="-- Synplicity black box declaration"
text017="attribute syn_black_box : boolean;"
text018="attribute syn_black_box of mux3to1_4bits: component is true;"
text019=""
text020=" "
text021="-------------------------------------------------------------"
text022=" "
text023="-- The following code must appear in the VHDL architecture body."
text024="-- Substitute your own instance name and net names."
text025=" "
text026="your_instance_name : mux3to1_4bits"
text027="        port map ("
text028="            MA => MA,"
text029="            MB => MB,"
text030="            MC => MC,"
text031="            MD => MD,"
text032="            S => S,"
text033="            O => O);"
text034=" "
[COREGEN.VERILOG Component Instantiation.mux3to1_4bits]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux3to1_4bits YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .MC(MC),"
text010="    .MD(MD),"
text011="    .S(S),"
text012="    .O(O));"
text013=""
text014=" "
[COREGEN.VHDL Component Instantiation.mux2to1_4bits]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux2to1_4bits"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(3 downto 0);"
text007="    MB: IN std_logic_VECTOR(3 downto 0);"
text008="    S: IN std_logic_VECTOR(0 downto 0);"
text009="    O: OUT std_logic_VECTOR(3 downto 0));"
text010="end component;"
text011=""
text012=""
text013=""
text014="-- Synplicity black box declaration"
text015="attribute syn_black_box : boolean;"
text016="attribute syn_black_box of mux2to1_4bits: component is true;"
text017=""
text018=" "
text019="-------------------------------------------------------------"
text020=" "
text021="-- The following code must appear in the VHDL architecture body."
text022="-- Substitute your own instance name and net names."
text023=" "
text024="your_instance_name : mux2to1_4bits"
text025="        port map ("
text026="            MA => MA,"
text027="            MB => MB,"
text028="            S => S,"
text029="            O => O);"
text030=" "
[COREGEN.VERILOG Component Instantiation.mux2to1_4bits]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux2to1_4bits YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .S(S),"
text010="    .O(O));"
text011=""
text012=" "
