[COREGEN.VHDL Component Instantiation.mux4to1_16bits]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux4to1_16bits"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(15 downto 0);"
text007="    MB: IN std_logic_VECTOR(15 downto 0);"
text008="    S: IN std_logic_VECTOR(0 downto 0);"
text009="    O: OUT std_logic_VECTOR(15 downto 0));"
text010="end component;"
text011=""
text012=""
text013=""
text014="-- Synplicity black box declaration"
text015="attribute syn_black_box : boolean;"
text016="attribute syn_black_box of mux4to1_16bits: component is true;"
text017=""
text018=" "
text019="-------------------------------------------------------------"
text020=" "
text021="-- The following code must appear in the VHDL architecture body."
text022="-- Substitute your own instance name and net names."
text023=" "
text024="your_instance_name : mux4to1_16bits"
text025="        port map ("
text026="            MA => MA,"
text027="            MB => MB,"
text028="            S => S,"
text029="            O => O);"
text030=" "
[COREGEN.VERILOG Component Instantiation.mux4to1_16bits]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux4to1_16bits YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .S(S),"
text010="    .O(O));"
text011=""
text012=" "
[COREGEN.VHDL Component Instantiation.mux_four]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux_four"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(15 downto 0);"
text007="    MB: IN std_logic_VECTOR(15 downto 0);"
text008="    MC: IN std_logic_VECTOR(15 downto 0);"
text009="    MD: IN std_logic_VECTOR(15 downto 0);"
text010="    S: IN std_logic_VECTOR(1 downto 0);"
text011="    O: OUT std_logic_VECTOR(15 downto 0));"
text012="end component;"
text013=""
text014=""
text015=""
text016="-- Synplicity black box declaration"
text017="attribute syn_black_box : boolean;"
text018="attribute syn_black_box of mux_four: component is true;"
text019=""
text020=" "
text021="-------------------------------------------------------------"
text022=" "
text023="-- The following code must appear in the VHDL architecture body."
text024="-- Substitute your own instance name and net names."
text025=" "
text026="your_instance_name : mux_four"
text027="        port map ("
text028="            MA => MA,"
text029="            MB => MB,"
text030="            MC => MC,"
text031="            MD => MD,"
text032="            S => S,"
text033="            O => O);"
text034=" "
[COREGEN.VERILOG Component Instantiation.mux_four]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux_four YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .MC(MC),"
text010="    .MD(MD),"
text011="    .S(S),"
text012="    .O(O));"
text013=""
text014=" "
[COREGEN.VHDL Component Instantiation.mux2_16bits]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux2_16bits"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(15 downto 0);"
text007="    MB: IN std_logic_VECTOR(15 downto 0);"
text008="    S: IN std_logic_VECTOR(0 downto 0);"
text009="    O: OUT std_logic_VECTOR(15 downto 0));"
text010="end component;"
text011=""
text012=""
text013=""
text014="-- Synplicity black box declaration"
text015="attribute syn_black_box : boolean;"
text016="attribute syn_black_box of mux2_16bits: component is true;"
text017=""
text018=" "
text019="-------------------------------------------------------------"
text020=" "
text021="-- The following code must appear in the VHDL architecture body."
text022="-- Substitute your own instance name and net names."
text023=" "
text024="your_instance_name : mux2_16bits"
text025="        port map ("
text026="            MA => MA,"
text027="            MB => MB,"
text028="            S => S,"
text029="            O => O);"
text030=" "
[COREGEN.VERILOG Component Instantiation.mux2_16bits]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux2_16bits YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .S(S),"
text010="    .O(O));"
text011=""
text012=" "
[COREGEN.VHDL Component Instantiation.mux4_16bits]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux4_16bits"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(15 downto 0);"
text007="    MB: IN std_logic_VECTOR(15 downto 0);"
text008="    S: IN std_logic_VECTOR(0 downto 0);"
text009="    O: OUT std_logic_VECTOR(15 downto 0));"
text010="end component;"
text011=""
text012=""
text013=""
text014="-- Synplicity black box declaration"
text015="attribute syn_black_box : boolean;"
text016="attribute syn_black_box of mux4_16bits: component is true;"
text017=""
text018=" "
text019="-------------------------------------------------------------"
text020=" "
text021="-- The following code must appear in the VHDL architecture body."
text022="-- Substitute your own instance name and net names."
text023=" "
text024="your_instance_name : mux4_16bits"
text025="        port map ("
text026="            MA => MA,"
text027="            MB => MB,"
text028="            S => S,"
text029="            O => O);"
text030=" "
[COREGEN.VERILOG Component Instantiation.mux4_16bits]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux4_16bits YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .S(S),"
text010="    .O(O));"
text011=""
text012=" "
[COREGEN.VHDL Component Instantiation.mux4_16bits_new]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux4_16bits_new"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(15 downto 0);"
text007="    MB: IN std_logic_VECTOR(15 downto 0);"
text008="    MC: IN std_logic_VECTOR(15 downto 0);"
text009="    MD: IN std_logic_VECTOR(15 downto 0);"
text010="    S: IN std_logic_VECTOR(1 downto 0);"
text011="    O: OUT std_logic_VECTOR(15 downto 0));"
text012="end component;"
text013=""
text014=""
text015=""
text016="-- Synplicity black box declaration"
text017="attribute syn_black_box : boolean;"
text018="attribute syn_black_box of mux4_16bits_new: component is true;"
text019=""
text020=" "
text021="-------------------------------------------------------------"
text022=" "
text023="-- The following code must appear in the VHDL architecture body."
text024="-- Substitute your own instance name and net names."
text025=" "
text026="your_instance_name : mux4_16bits_new"
text027="        port map ("
text028="            MA => MA,"
text029="            MB => MB,"
text030="            MC => MC,"
text031="            MD => MD,"
text032="            S => S,"
text033="            O => O);"
text034=" "
[COREGEN.VERILOG Component Instantiation.mux4_16bits_new]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux4_16bits_new YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .MC(MC),"
text010="    .MD(MD),"
text011="    .S(S),"
text012="    .O(O));"
text013=""
text014=" "
