[COREGEN.VHDL Component Instantiation.mux2to1]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux2to1"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(3 downto 0);"
text007="    MB: IN std_logic_VECTOR(3 downto 0);"
text008="    S: IN std_logic_VECTOR(0 downto 0);"
text009="    O: OUT std_logic_VECTOR(3 downto 0));"
text010="end component;"
text011=""
text012=""
text013=""
text014="-- Synplicity black box declaration"
text015="attribute syn_black_box : boolean;"
text016="attribute syn_black_box of mux2to1: component is true;"
text017=""
text018=" "
text019="-------------------------------------------------------------"
text020=" "
text021="-- The following code must appear in the VHDL architecture body."
text022="-- Substitute your own instance name and net names."
text023=" "
text024="your_instance_name : mux2to1"
text025="        port map ("
text026="            MA => MA,"
text027="            MB => MB,"
text028="            S => S,"
text029="            O => O);"
text030=" "
[COREGEN.VERILOG Component Instantiation.mux2to1]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux2to1 YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .S(S),"
text010="    .O(O));"
text011=""
text012=" "
[COREGEN.VHDL Component Instantiation.mux8to1]
type=template
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mux8to1"
text005="    port ("
text006="    MA: IN std_logic_VECTOR(3 downto 0);"
text007="    MB: IN std_logic_VECTOR(3 downto 0);"
text008="    MC: IN std_logic_VECTOR(3 downto 0);"
text009="    MD: IN std_logic_VECTOR(3 downto 0);"
text010="    ME: IN std_logic_VECTOR(3 downto 0);"
text011="    MF: IN std_logic_VECTOR(3 downto 0);"
text012="    MG: IN std_logic_VECTOR(3 downto 0);"
text013="    MH: IN std_logic_VECTOR(3 downto 0);"
text014="    S: IN std_logic_VECTOR(2 downto 0);"
text015="    O: OUT std_logic_VECTOR(3 downto 0));"
text016="end component;"
text017=""
text018=""
text019=""
text020="-- Synplicity black box declaration"
text021="attribute syn_black_box : boolean;"
text022="attribute syn_black_box of mux8to1: component is true;"
text023=""
text024=" "
text025="-------------------------------------------------------------"
text026=" "
text027="-- The following code must appear in the VHDL architecture body."
text028="-- Substitute your own instance name and net names."
text029=" "
text030="your_instance_name : mux8to1"
text031="        port map ("
text032="            MA => MA,"
text033="            MB => MB,"
text034="            MC => MC,"
text035="            MD => MD,"
text036="            ME => ME,"
text037="            MF => MF,"
text038="            MG => MG,"
text039="            MH => MH,"
text040="            S => S,"
text041="            O => O);"
text042=" "
[COREGEN.VERILOG Component Instantiation.mux8to1]
type=template
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mux8to1 YourInstanceName ("
text007="    .MA(MA),"
text008="    .MB(MB),"
text009="    .MC(MC),"
text010="    .MD(MD),"
text011="    .ME(ME),"
text012="    .MF(MF),"
text013="    .MG(MG),"
text014="    .MH(MH),"
text015="    .S(S),"
text016="    .O(O));"
text017=""
text018=" "
